(function(){
  function repairPage(){var walker=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT);var node;while(node=walker.nextNode()){node.nodeValue=node.nodeValue.replace(/\u06b7/g,' \u00b7 ').replace(/\u00da\u00b7/g,' \u00b7 ')}}
  function persona(idea){var data={
    'La Butaca Pepinera':{name:'Javier Martín · 52',role:'Abonado fiel con poco tiempo',title:'Javier no necesita otra app. Necesita que sea fácil.',text:'Trabaja con turnos cambiantes y lleva más de quince años junto al Lega. Valora la rapidez, la justicia y que su fidelidad sea reconocida.',quote:'Quiero ceder mi asiento sin perder valor.',image:'persona-javier.png'},
    'Desbloquea Butarque':{name:'Lucía Hernández · 22',role:'Aficionada digital y creadora emergente',title:'Lucía quiere un papel real, no una campaña artificial.',text:'Estudia comunicación audiovisual y descubre el Lega en TikTok, Instagram y YouTube. Busca amigos, participación y algo que no pueda vivir desde casa.',quote:'Quiero que el estadio me dé una historia.',image:'persona-lucia.jpg'},
    'Butarque Responde':{name:'Álvaro Sánchez · 34',role:'Miembro activo de una peña',title:'Álvaro no pide promesas. Pide participación real.',text:'Participa en una peña y organiza su semana alrededor del fútbol. Es directo, apasionado y puede convertirse en embajador si se le escucha de verdad.',quote:'La identidad de la grada también debe contar.',image:'persona-alvaro.png'},
    'Lega Pass':{name:'Lucía Hernández · 22',role:'Aficionada digital y creadora emergente',title:'Lucía quiere volver más veces sin comprometerse todo el año.',text:'Estudia, trabaja algunas horas y se mueve en transporte público. Busca una alternativa accesible para acudir con amigos y convertir su interés digital en hábito.',quote:'Quiero venir con mis amigos sin pagar un abono.',image:'persona-lucia.jpg'}
  };return data[idea]}
  function init(){
    repairPage();
    document.querySelectorAll('form[data-vote-form]').forEach(function(form){
      form.classList.add('vote-card');
      var voteSection=form.closest('section'),heading=voteSection&&voteSection.querySelector('h2'),intro=voteSection&&voteSection.querySelector('p'),legend=form.querySelector('legend'),submit=form.querySelector('button'),idea=form.querySelector('input[name="idea"]')?.value,profile=persona(idea?.trim());
      if(profile&&!document.querySelector('.persona-section')){var personaSection=document.createElement('section');personaSection.className='persona-section';personaSection.innerHTML='<div class="persona-inner"><div><p class="persona-kicker">Pensado para personas reales</p><h2>'+profile.title+'</h2><p class="persona-copy">'+profile.text+'</p></div><div class="persona-card"><img src="'+profile.image+'" alt="'+profile.name+'"><div><strong>'+profile.name+'</strong><span>'+profile.role+'</span><q>'+profile.quote+'</q></div></div></div>';voteSection.parentNode.insertBefore(personaSection,voteSection)}
      if(heading)heading.textContent='Haz que esta idea avance';
      if(intro)intro.textContent='Tu valoración convierte una buena intuición en una oportunidad real.';
      if(legend){legend.textContent='¿Cuánto la apoyarías?';legend.setAttribute('aria-label','Valoración obligatoria');var hint=document.createElement('p');hint.className='vote-hint';hint.textContent='Elige de 1 a 5 estrellas · obligatorio';legend.insertAdjacentElement('afterend',hint)}
      if(submit){submit.classList.add('vote-submit');submit.textContent='Apoyar esta idea →'}
      var radios=Array.from(form.querySelectorAll('.stars input[type="radio"]')),labels=Array.from(form.querySelectorAll('.stars label')),status=document.createElement('p');
      status.className='vote-status';form.querySelector('.stars').insertAdjacentElement('afterend',status);
      var reactions={1:'😕',2:'🤔',3:'🙂',4:'🔥',5:'🚀'};labels.forEach(function(label){var value=label.htmlFor.replace(/\D/g,'');label.style.order=value;label.innerHTML='<span class="vote-emoji">'+reactions[value]+'</span><small>'+value+'</small>'});function syncStars(){var selected=Number((radios.find(function(radio){return radio.checked})||{}).value||0);labels.forEach(function(label){var radio=document.getElementById(label.htmlFor);label.classList.toggle('active',!!radio&&Number(radio.value)<=selected)});status.textContent=selected?selected+'/5 · '+['','Todavía necesita trabajo','Puede mejorar','Tiene potencial','Muy buena oportunidad','Quiero verla en marcha'][selected]:'Aún no has elegido una valoración'}
      radios.forEach(function(radio){radio.setAttribute('aria-label',radio.value+' de 5 estrellas');radio.addEventListener('change',syncStars)});labels.forEach(function(label){label.title='Seleccionar '+label.htmlFor.replace(/\D/g,'')+' estrellas'});syncStars();
      form.addEventListener('submit',async function(event){
        event.preventDefault();var endpoint=window.XP_VOTE_ENDPOINT,button=form.querySelector('button[type="submit"],button:not([type])');
        if(!endpoint||endpoint.indexOf('PASTE_')===0){alert('Configura primero el endpoint de votación.');return}
        if(button){button.disabled=true;button.dataset.originalText=button.textContent;button.textContent='Guardando tu apoyo…'}
        try{var data=Object.fromEntries(new FormData(form).entries());data.page=location.pathname;data.submitted_at=new Date().toISOString();var ipResponse=await fetch('https://api64.ipify.org?format=json'),ipData=await ipResponse.json();data.client_ip=ipData.ip;try{var geoResponse=await fetch('https://ipapi.co/'+encodeURIComponent(data.client_ip)+'/json/'),geo=await geoResponse.json();data.country=geo.country_name||'';data.city=geo.city||''}catch(geoError){data.country='';data.city=''}var response=await fetch(endpoint,{method:'POST',mode:'cors',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify(data)}),result=await response.json();if(!result.ok){alert(result.message||'No se pudo registrar el voto.');return}form.reset();syncStars();var remaining=typeof result.remaining==='number'?' Te quedan '+result.remaining+' votos por esta idea.':'';alert('¡Gracias! Tu apoyo se ha registrado correctamente.'+remaining)}catch(error){alert('No se pudo guardar el voto. Inténtalo de nuevo.')}finally{if(button){button.disabled=false;button.textContent=button.dataset.originalText}}});
    });
  }
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
